/**
 * Hindi Legal Terms Dictionary
 * Maps English legal terms to Hindi (Devanagari) equivalents.
 * Used by: client UI (when language=hi), server system prompts, document generation.
 */

export const HINDI_LEGAL_TERMS: Record<string, string> = {
  // ─── Court & Judiciary ───────────────────────────────────────────
  "Supreme Court": "सर्वोच्च न्यायालय",
  "High Court": "उच्च न्यायालय",
  "District Court": "जिला न्यायालय",
  "Sessions Court": "सत्र न्यायालय",
  "Magistrate Court": "मजिस्ट्रेट न्यायालय",
  "Family Court": "पारिवारिक न्यायालय",
  "Consumer Court": "उपभोक्ता न्यायालय",
  "Tribunal": "अधिकरण",
  "Bench": "पीठ",
  "Division Bench": "खंडपीठ",
  "Full Bench": "पूर्णपीठ",
  "Judge": "न्यायाधीश",
  "Chief Justice": "मुख्य न्यायाधीश",
  "Magistrate": "मजिस्ट्रेट",
  "Registrar": "पंजीकार",

  // ─── Parties ─────────────────────────────────────────────────────
  "Petitioner": "याचिकाकर्ता",
  "Respondent": "प्रत्यर्थी",
  "Appellant": "अपीलकर्ता",
  "Plaintiff": "वादी",
  "Defendant": "प्रतिवादी",
  "Complainant": "शिकायतकर्ता",
  "Accused": "अभियुक्त",
  "Applicant": "आवेदक",
  "Deponent": "शपथकर्ता",
  "Witness": "गवाह",
  "Prosecution": "अभियोजन",
  "Defence": "बचाव पक्ष",
  "Advocate": "अधिवक्ता",
  "Senior Advocate": "वरिष्ठ अधिवक्ता",
  "Public Prosecutor": "लोक अभियोजक",
  "Attorney General": "महान्यायवादी",
  "Solicitor General": "सॉलिसिटर जनरल",

  // ─── Document Types ──────────────────────────────────────────────
  "Petition": "याचिका",
  "Writ Petition": "रिट याचिका",
  "Appeal": "अपील",
  "Bail Application": "जमानत आवेदन",
  "Bail": "जमानत",
  "Anticipatory Bail": "अग्रिम जमानत",
  "FIR": "प्रथम सूचना रिपोर्ट (FIR)",
  "Chargesheet": "आरोप पत्र",
  "Affidavit": "शपथपत्र",
  "Legal Notice": "कानूनी नोटिस",
  "Complaint": "शिकायत",
  "Written Statement": "लिखित कथन",
  "Rejoinder": "प्रत्युत्तर",
  "Counter Affidavit": "प्रति शपथपत्र",
  "Plaint": "वाद पत्र",
  "Suit": "वाद",
  "Revision": "पुनरीक्षण",
  "Review": "पुनर्विलोकन",
  "Application": "आवेदन",
  "Contract": "अनुबंध",
  "Agreement": "करार",
  "Power of Attorney": "मुख्तारनामा",
  "Deed": "विलेख",
  "Will": "वसीयत",
  "Trust Deed": "न्यास विलेख",
  "Vakalatnama": "वकालतनामा",

  // ─── Legal Concepts ──────────────────────────────────────────────
  "Judgement": "निर्णय",
  "Order": "आदेश",
  "Decree": "डिक्री",
  "Interim Order": "अंतरिम आदेश",
  "Stay Order": "स्थगन आदेश",
  "Injunction": "निषेधाज्ञा",
  "Hearing": "सुनवाई",
  "Next Date": "अगली तारीख",
  "Evidence": "साक्ष्य",
  "Cross Examination": "जिरह",
  "Examination in Chief": "मुख्य परीक्षा",
  "Arguments": "बहस",
  "Jurisdiction": "अधिकार क्षेत्र",
  "Limitation": "परिसीमा",
  "Limitation Period": "परिसीमा अवधि",
  "Cause of Action": "वाद हेतुक",
  "Locus Standi": "वाद अधिकार",
  "Res Judicata": "पूर्व न्याय",
  "Precedent": "पूर्व निर्णय",
  "Ratio Decidendi": "निर्णय का आधार",
  "Obiter Dictum": "प्रासंगिक टिप्पणी",
  "Contempt of Court": "न्यायालय की अवमानना",
  "Perjury": "मिथ्या शपथ",

  // ─── Procedures ──────────────────────────────────────────────────
  "Filing": "दाखिल करना",
  "Service": "तामील",
  "Summons": "समन",
  "Warrant": "वारंट",
  "Arrest": "गिरफ्तारी",
  "Remand": "रिमांड",
  "Custody": "हिरासत",
  "Judicial Custody": "न्यायिक हिरासत",
  "Police Custody": "पुलिस हिरासत",
  "Investigation": "जांच",
  "Inquiry": "पूछताछ",
  "Trial": "विचारण",
  "Acquittal": "दोषमुक्ति",
  "Conviction": "दोषसिद्धि",
  "Sentence": "सजा",
  "Execution": "निष्पादन",
  "Attachment": "कुर्की",
  "Auction": "नीलामी",

  // ─── Practice Areas ──────────────────────────────────────────────
  "Criminal Law": "आपराधिक कानून",
  "Civil Law": "सिविल कानून",
  "Family Law": "पारिवारिक कानून",
  "Corporate Law": "कॉर्पोरेट कानून",
  "Labour Law": "श्रम कानून",
  "Property Law": "संपत्ति कानून",
  "Tax Law": "कर कानून",
  "Constitutional Law": "संवैधानिक कानून",
  "Intellectual Property": "बौद्धिक संपदा",
  "Consumer Law": "उपभोक्ता कानून",
  "Cyber Law": "साइबर कानून",
  "Environmental Law": "पर्यावरण कानून",
  "Banking Law": "बैंकिंग कानून",
  "Arbitration": "मध्यस्थता",
  "Immigration": "आप्रवासन",

  // ─── Statutes (New Criminal Codes) ───────────────────────────────
  "Bharatiya Nyaya Sanhita": "भारतीय न्याय संहिता",
  "Bharatiya Nagarik Suraksha Sanhita": "भारतीय नागरिक सुरक्षा संहिता",
  "Bharatiya Sakshya Adhiniyam": "भारतीय साक्ष्य अधिनियम",
  "Indian Penal Code": "भारतीय दंड संहिता",
  "Code of Criminal Procedure": "दंड प्रक्रिया संहिता",
  "Indian Evidence Act": "भारतीय साक्ष्य अधिनियम",
  "Constitution of India": "भारत का संविधान",
  "Limitation Act": "परिसीमा अधिनियम",
  "Transfer of Property Act": "संपत्ति अंतरण अधिनियम",
  "Indian Contract Act": "भारतीय अनुबंध अधिनियम",
  "Negotiable Instruments Act": "परक्राम्य लिखत अधिनियम",
  "Companies Act": "कंपनी अधिनियम",
  "Hindu Marriage Act": "हिंदू विवाह अधिनियम",
  "Muslim Personal Law": "मुस्लिम पर्सनल लॉ",
  "Special Marriage Act": "विशेष विवाह अधिनियम",
  "Arbitration and Conciliation Act": "मध्यस्थता और सुलह अधिनियम",
  "Information Technology Act": "सूचना प्रौद्योगिकी अधिनियम",
  "Right to Information Act": "सूचना का अधिकार अधिनियम",

  // ─── Common Legal Phrases ────────────────────────────────────────
  "Whereas": "जबकि",
  "Therefore": "अतः",
  "Hereinafter": "इसके बाद",
  "In the matter of": "विषय में",
  "In pursuance of": "के अनुसरण में",
  "Without prejudice": "अधिकार पूर्वक",
  "Under Section": "धारा के अंतर्गत",
  "As per": "के अनुसार",
  "Notwithstanding": "के बावजूद",
  "Subject to": "के अधीन",
  "In accordance with": "के अनुसार",
  "Null and void": "शून्य एवं अमान्य",
  "Bona fide": "सद्भावनापूर्वक",
} as const;

export type HindiLegalTerm = keyof typeof HINDI_LEGAL_TERMS;
